# Generated by Django 5.2.9 on 2025-12-09 18:07

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('titulo', 0), ('paragrafo', 1), ('citacao', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.BlockQuoteBlock', (), {})}, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='texto_boas_vindas',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
