# Generated by Django 5.2.9 on 2025-12-11 13:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blogpage_main_image_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('titulo', 0), ('paragrafo', 1), ('codigo', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('html', 'HTML'), ('bash', 'Terminal')], 'label': 'Linguagem'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Cole seu código aqui'}), 4: ('wagtail.blocks.StructBlock', [[('linguagem', 2), ('code_text', 3)]], {'icon': 'code'})}),
        ),
    ]
