# Generated by Django 5.2.9 on 2025-12-15 16:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blogpagetag_blogpage_tags'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=250, verbose_name='Introdução')),
                ('body', wagtail.fields.StreamField([('titulo', 0), ('paragrafo', 1), ('codigo', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('html', 'HTML'), ('bash', 'Terminal')], 'label': 'Linguagem'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Cole seu código aqui'}), 4: ('wagtail.blocks.StructBlock', [[('linguagem', 2), ('code_text', 3)]], {'icon': 'code'})})),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
